const langArray = {
  english: {
    myName: "Nakul",
    GptSearchPlaceholder: "Search for your next binge-worthy series...",
    Howdy: "Howdy",
    LogOut: "Log Out",
    Play: "Play Now",
    LessInfo: "Less Info",
    MoreInfo: "More Info",
    Rating: "Rating",
    Warning1: "Please write something in Search Box",
    NowPlaying: "Now Playing",
    Popular: "Popular",
    TopRated: "Top Rated",
    Upcoming: "Upcoming",
    Related: "Related",
    Close: "Close",
    Added: "Added",
    AddToList: "Add to List",
    Watchlist: "Watchlist",
    YourWatchlist: "Your Watchlist",
    OldestFirst: "Oldest First",
    NewestFirst: "Newest First",
    YourWatchlistIsEmpty: "Your Watchlist is Empty!",
    ClearAll: "Clear All",
    SearchResults: "Search Results",
    TodayTrending: "Today Trending",
    PopupInfo: `The search bar allows you to search for any movie name, providing quick access to detailed movie information. If you're unsure of what to watch, simply type in a query like "Suggest me new funny movies" for recommendations. It intelligently fetches relevant movie suggestions based on your input. Enjoy discovering new films effortlessly with this versatile search feature.`,
    WatchTrailer: "Watch Trailer",
    Genre: "Genre",
  },
  hindi: {
    myName: "नकुल",
    GptSearchPlaceholder: "अपनी अगली फिल्म खोजें...",
    Howdy: "कैसे हो",
    LogOut: "लॉग आउट",
    Play: "शुरू करें",
    LessInfo: "कम जानकारी",
    MoreInfo: "अधिक जानकारी",
    Rating: "रेटिंग",
    Warning1: "कृपया सर्च बॉक्स में कुछ लिखें",
    NowPlaying: "थिएटर में",
    Popular: "लोकप्रिय",
    TopRated: "टॉप रेटेड",
    Upcoming: "आगामी",
    Related: "संबंधित",
    Close: "बंद करें",
    Added: "जोड़ दिया गया",
    AddToList: "लिस्ट में जोडे",
    Watchlist: "देखने की सूची",
    YourWatchlist: "आपकी सूची",
    OldestFirst: "सबसे पुराना पहले",
    NewestFirst: "नवीनतम पहले",
    YourWatchlistIsEmpty: "आपकी वॉचलिस्ट खाली है!",
    ClearAll: "सभी साफ करें",
    SearchResults: "खोज के परिणाम",
    TodayTrending: "आज ट्रेंडिंग",
    PopupInfo: `खोज बार आपको किसी भी फिल्म का नाम खोजने की अनुमति देता है, जो विस्तृत फिल्म जानकारी तक त्वरित पहुंच प्रदान करता है। यदि आप निश्चित नहीं हैं कि क्या देखना है, तो अनुशंसाओं के लिए बस "मुझे नई मजेदार फिल्में सुझाएं" जैसी क्वेरी टाइप करें। यह आपके इनपुट के आधार पर समझदारी से प्रासंगिक मूवी सुझाव लाता है। इस बहुमुखी खोज सुविधा के साथ सहजता से नई फिल्में खोजने का आनंद लें।`,
    WatchTrailer: "ट्रेलर देखें",
    Genre: "शैली",
  },
  spanish: {
    myName: "Nakul",
    GptSearchPlaceholder: "Busca tu próxima serie digna de un atracón...",
    Howdy: "Hola",
    LogOut: "Cerrar sesión",
    Play: "Comenzar",
    LessInfo: "Menos información",
    MoreInfo: "Más información",
    Rating: "Clasificación",
    Warning1: "Por favor escribe algo en el cuadro de búsqueda.",
    NowPlaying: "Jugando en el Teatro",
    Popular: "Popular",
    TopRated: "Los más valorados",
    Upcoming: "Próximo",
    Related: "Relacionado",
    Close: "Cerca",
    Added: "Agregado",
    AddToList: "Agregar a la lista",
    Watchlist: "Lista de vigilancia",
    YourWatchlist: "Tu lista de seguimiento",
    OldestFirst: "Los más viejos primero",
    NewestFirst: "El más reciente primero",
    YourWatchlistIsEmpty: "Tu lista de seguimiento está vacía!",
    ClearAll: "Limpiar todo",
    SearchResults: "Resultados de la búsqueda",
    TodayTrending: "Hoy Tendencias",
    PopupInfo: `La barra de búsqueda le permite buscar cualquier nombre de película, brindando acceso rápido a información detallada de la película. Si no está seguro de qué ver, simplemente escriba una consulta como "Sugiérame nuevas películas divertidas" para obtener recomendaciones. Recupera de forma inteligente sugerencias de películas relevantes en función de sus comentarios. Disfrute descubriendo nuevas películas sin esfuerzo con esta versátil función de búsqueda.`,
    WatchTrailer: "Ver el trailer",
    Genre: "Género",
  },
  french: {
    myName: "Nakul",
    GptSearchPlaceholder:
      "Recherchez votre prochaine série digne d'être frénésie...",
    Howdy: "Salut",
    LogOut: "Se déconnecter",
    Play: "Commencer",
    LessInfo: "Moins d'informations",
    MoreInfo: "Plus d'informations",
    Rating: "Notation",
    Warning1: "Veuillez saisir quelque chose dans le champ de recherche.",
    NowPlaying: "Jouer au théâtre",
    Popular: "Popular",
    TopRated: "Les mieux notés",
    Upcoming: "Suivant",
    Related: "Rapport",
    Close: "Fermer",
    Added: "Ajouté",
    AddToList: "Ajouter à la liste",
    Watchlist: "Liste de surveillance",
    YourWatchlist: "Votre liste de surveillance",
    OldestFirst: "Le plus ancienPremier",
    NewestFirst: "Le plus récent d'abord",
    YourWatchlistIsEmpty: "Votre liste de surveillance est vide!",
    ClearAll: "Tout effacer",
    SearchResults: "Résultats de recherche",
    TodayTrending: "Tendance du jour",
    PopupInfo: `La barre de recherche vous permet de rechercher n'importe quel nom de film, offrant un accès rapide aux informations détaillées sur le film. Si vous ne savez pas quoi regarder, tapez simplement une requête telle que « Suggérez-moi de nouveaux films amusants » pour obtenir des recommandations. Il récupère intelligemment des suggestions de films pertinentes en fonction de vos commentaires. Profitez de la découverte de nouveaux films sans effort grâce à cette fonction de recherche polyvalente.`,
    WatchTrailer: "Regarde la bande-annonce",
    Genre: "Genre",
  },
};

export default langArray;
