const langArray = {
  english: {
    myName: "Nakul",
    GptSearchPlaceholder: "Search for your next binge-worthy series...",
    Howdy: "Howdy",
    LogOut: "Log Out",
    Play: "Play Now",
    LessInfo: "Less Info",
    MoreInfo: "More Info",
    Rating: "Rating",
    Warning1: "Please write something in Search Box",
    NowPlaying: "Now Playing",
    Popular: "Popular",
    TopRated: "Top Rated",
    Upcoming: "Upcoming",
    Related: "Related",
    Close: "Close",
    Added: "Added",
    AddToList: "Add to List",
    Watchlist: "Watchlist",
    YourWatchlist: "Your Watchlist",
    OldestFirst: "Oldest First",
    NewestFirst: "Newest First",
    YourWatchlistIsEmpty: "Your Watchlist is Empty!",
    ClearAll: "Clear All",
    SearchResults: "Search Results",
    TodayTrending: "Today Trending",
  },
  hindi: {
    myName: "नकुल",
    GptSearchPlaceholder: "अपनी अगली फिल्म खोजें...",
    Howdy: "कैसे हो",
    LogOut: "लॉग आउट",
    Play: "शुरू करें",
    LessInfo: "कम जानकारी",
    MoreInfo: "अधिक जानकारी",
    Rating: "रेटिंग",
    Warning1: "कृपया सर्च बॉक्स में कुछ लिखें",
    NowPlaying: "थिएटर में",
    Popular: "लोकप्रिय",
    TopRated: "टॉप रेटेड",
    Upcoming: "आगामी",
    Related: "संबंधित",
    Close: "बंद करें",
    Added: "जोड़ दिया गया",
    AddToList: "लिस्ट में जोडे",
    Watchlist: "देखने की सूची",
    YourWatchlist: "आपकी सूची",
    OldestFirst: "सबसे पुराना पहले",
    NewestFirst: "नवीनतम पहले",
    YourWatchlistIsEmpty: "आपकी वॉचलिस्ट खाली है!",
    ClearAll: "सभी साफ करें",
    SearchResults: "खोज के परिणाम",
    TodayTrending: "आज ट्रेंडिंग",
  },
  spanish: {
    myName: "Nakul",
    GptSearchPlaceholder: "Busca tu próxima serie digna de un atracón...",
    Howdy: "Hola",
    LogOut: "Cerrar sesión",
    Play: "Comenzar",
    LessInfo: "Menos información",
    MoreInfo: "Más información",
    Rating: "Clasificación",
    Warning1: "Por favor escribe algo en el cuadro de búsqueda.",
    NowPlaying: "Jugando en el Teatro",
    Popular: "Popular",
    TopRated: "Los más valorados",
    Upcoming: "Próximo",
    Related: "Relacionado",
    Close: "Cerca",
    Added: "Agregado",
    AddToList: "Agregar a la lista",
    Watchlist: "Lista de vigilancia",
    YourWatchlist: "Tu lista de seguimiento",
    OldestFirst: "Los más viejos primero",
    NewestFirst: "El más reciente primero",
    YourWatchlistIsEmpty: "Tu lista de seguimiento está vacía!",
    ClearAll: "Limpiar todo",
    SearchResults: "Resultados de la búsqueda",
    TodayTrending: "Hoy Tendencias",
  },
  french: {
    myName: "Nakul",
    GptSearchPlaceholder:
      "Recherchez votre prochaine série digne d'être frénésie...",
    Howdy: "Salut",
    LogOut: "Se déconnecter",
    Play: "Commencer",
    LessInfo: "Moins d'informations",
    MoreInfo: "Plus d'informations",
    Rating: "Notation",
    Warning1: "Veuillez saisir quelque chose dans le champ de recherche.",
    NowPlaying: "Jouer au théâtre",
    Popular: "Popular",
    TopRated: "Les mieux notés",
    Upcoming: "Suivant",
    Related: "Rapport",
    Close: "Fermer",
    Added: "Ajouté",
    AddToList: "Ajouter à la liste",
    Watchlist: "Liste de surveillance",
    YourWatchlist: "Votre liste de surveillance",
    OldestFirst: "Le plus ancienPremier",
    NewestFirst: "Le plus récent d'abord",
    YourWatchlistIsEmpty: "Votre liste de surveillance est vide!",
    ClearAll: "Tout effacer",
    SearchResults: "Résultats de recherche",
    TodayTrending: "Tendance du jour",
  },
};

export default langArray;
